[build]
  command = "npm install && npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22.11.0"
  NPM_FLAGS = "--prefer-offline --no-audit"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Configuration pour les fonctions serverless
[functions]
  directory = ".output/server"

# Redirections pour les API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirections SPA pour les routes client
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
