[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--prefer-offline --no-audit"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Configuration pour les fonctions serverless
[functions]
  directory = ".netlify/functions"

# Redirections pour les API routes
[[redirects]]
  from = "/api/movies/popular"
  to = "/.netlify/functions/movies-popular"
  status = 200

[[redirects]]
  from = "/api/movies/now-playing"
  to = "/.netlify/functions/movies-now-playing"
  status = 200

[[redirects]]
  from = "/api/movies/top-rated"
  to = "/.netlify/functions/movies-top-rated"
  status = 200

[[redirects]]
  from = "/api/movies/discover"
  to = "/.netlify/functions/movies-discover"
  status = 200

# Redirections SPA pour les routes client
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
