[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--prefer-offline --no-audit"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Configuration pour les fonctions serverless
[functions]
  directory = ".netlify/functions"

# Test de la fonction Netlify
[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200

# Redirections pour les API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Redirections SPA pour les routes client
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
